services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    ports:
      - "8000:8000"
    networks:
      - lite-logging

networks:
  lite-logging:
    external: true
