name: Version Check

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  version-check:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for tags

      - name: Check version consistency
        run: |
          # Get current version from pyproject.toml
          CURRENT_VERSION=$(grep "^version" pyproject.toml | sed 's/version = "\(.*\)"/\1/')
          echo "Current version in pyproject.toml: $CURRENT_VERSION"
          
          # Get latest git tag
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "no-tags")
          if [ "$LATEST_TAG" != "no-tags" ]; then
            LATEST_VERSION=${LATEST_TAG#v}
            echo "Latest git tag version: $LATEST_VERSION"
            
            # Compare versions
            if [ "$CURRENT_VERSION" != "$LATEST_VERSION" ]; then
              echo "⚠️  Version mismatch detected!"
              echo "pyproject.toml version: $CURRENT_VERSION"
              echo "Latest git tag version: $LATEST_VERSION"
              echo "Consider updating the version or creating a new tag."
            else
              echo "✅ Version is consistent between pyproject.toml and git tag"
            fi
          else
            echo "ℹ️  No git tags found"
          fi 